services:

  cuda-ipc-memory-manager-service:
    build: .
    #runtime: nvidia
    network_mode: host
    restart: unless-stopped
    environment:
      - SPDLOG_LEVEL=TRACE
      - GPU_INDEX_DEVICE=0
      - ZMQ_ROUTER_ENDPOINT=ipc:///var/run/cuda-ipc-memory-manager-service.ipc
      - PROMETHEUS_ENDPOINT=0.0.0.0:9242
    volumes:
      - zmq_ipc_socket:/var/run/
    privileged: true
    command: [ "/app/cuda-ipc-memory-manager-service", "--config", "/app/config/config.tpl" ]

volumes:
  zmq_ipc_socket:
