services:

  cuda-ipc-memory-manager-service:
    build: .
    network_mode: host
    restart: unless-stopped
    ipc: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - SPDLOG_LEVEL=TRACE
      - GPU_UUID_0=ab29f361-2479-f8c8-f2e2-a56c3692a3ac
      - GPU_UUID_1=b9d111bf-dcea-67b5-acba-63b8c6efa84c
      - ZMQ_ROUTER_ENDPOINT=ipc:///tmp/cuda-ipc-memory-manager-service.ipc
      - PROMETHEUS_ENDPOINT=0.0.0.0:9242
    volumes:
      - /tmp:/tmp
    privileged: true
    command: [ "/app/cuda-ipc-memory-manager-service", "--config", "/app/config/two.gpu.tpl" ]

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  #zmq_ipc_socket:
  prometheus_data:
  grafana_data:
