services:

  cuda-ipc-memory-manager-service:
    build: .
    runtime: nvidia
    network_mode: host
    restart: unless-stopped
    #user: "1000:1000"
    environment:
      - SPDLOG_LEVEL=TRACE
      - GPU_INDEX_DEVICE=0
      - ZMQ_ROUTER_ENDPOINT=ipc:///tmp/cuda-ipc-memory-manager-service.ipc
      - PROMETHEUS_ENDPOINT=0.0.0.0:9242
    volumes:
      - /tmp:/tmp
    privileged: true
    command: [ "/app/cuda-ipc-memory-manager-service", "--config", "/app/config/config.tpl" ]

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  #zmq_ipc_socket:
  prometheus_data:
  grafana_data:
