{
 "title": "cuda-ipc-memory-manager",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocated Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "cuda_ipc_allocated_buffers", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Allocated Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "cuda_ipc_allocated_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Create Buffer Failure Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cuda_ipc_create_buffer_fail_total/(cuda_ipc_create_buffer_success_total+cuda_ipc_create_buffer_fail_total)\n",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Expired Buffer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_expired_buffers_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "API RPC Rate",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_create_buffer_latency_seconds_count[1m])\n",
     "legendFormat": "Create Buffer"
    },
    {
     "expr": "rate(cuda_ipc_create_buffer_latency_seconds_count[1m])\n",
     "legendFormat": "Create Buffer"
    },
    {
     "expr": "rate(cuda_ipc_notify_done_latency_seconds_count[1m])\n",
     "legendFormat": "Notify Done"
    }
   ]
  },
  {
   "title": "Create Buffer Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_create_buffer_latency_seconds_sum[1m]) / rate(cuda_ipc_create_buffer_latency_seconds_count[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Buffer Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_get_buffer_latency_seconds_sum[1m]) / rate(cuda_ipc_get_buffer_latency_seconds_count[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notify Done Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_notify_done_latency_seconds_sum[1m]) / rate(cuda_ipc_notify_done_latency_seconds_count[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Buffer Latency Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_create_buffer_latency_seconds_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get  Buffer Latency Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_get_buffer_latency_seconds_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Notify Done Latency Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "rate(cuda_ipc_notify_done_latency_seconds_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}